version: "3.8"

services:
    backend:
        build: ./backend
        env_file: ./.env
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
            - ${BACKEND_DEBUG_PORT}:${BACKEND_DEBUG_PORT}
        volumes:
            - ./backend/src:/app/src
            - ./backend/test:/app/test
        depends_on:
            - db

    frontend:
        build: ./frontend
        env_file: ./.env
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        volumes:
            - ./frontend/src:/app/src
        depends_on:
            - backend

    db:
        image: postgres:14.2-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${DB_PORT}:${DB_PORT}
